# -- Markup --
# These settings are required for the theme to function.

[goldmark]
[goldmark.renderer]
  unsafe = true

# https://discourse.gohugo.io/t/smartypants-conversion-issue-with-quotes/47942/2
[goldmark.extensions.typographer]
  disable = false
  apostrophe = '&apos;'
  ellipsis = '&hellip;'
  emDash = '&mdash;'
  enDash = '&ndash;'
  rightDoubleQuote = '&quot;'
  leftDoubleQuote = '&quot;'
  rightSingleQuote = '&apos;'
  leftSingleQuote = '&apos;'
  # rightAngleQuote = '&rsaquo;'
  # leftAngleQuote = '&lsaquo;'


[highlight]
  codeFences = false

[tableOfContents]
  startLevel = 1
  endLevel = 5 # 不包含 endLevel，所以只显示 1-2 级别。
