# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.



[[main]]
  name = "All Posts"
  pageRef = "posts/"
  weight = 10



[[main]]
  name = "Notes"
  weight = 20
  pageRef = "notes"

[[main]]
  name = "Personal Notes"
  parent = "Notes"
  weight = 10
  pageRef = "notes/personal"

[[main]]
  name = "Linux"
  parent = "Notes"
  pageRef = "notes/linux"
  weight = 20



[[main]]
  name = "Jottings"
  pageRef = "jottings"
  weight = 30



# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "About"
  pageRef = "about"
  weight = 10

[[footer]]
  name = "Tags"
  pageRef = "tags"
  weight = 20

[[footer]]
  name = "Categories"
  pageRef = "categories"
  weight = 30

#[[footer]]
#  name = "Series"
#  pageRef = "series"
#  weight = 30

[[footer]]
  name = "Archives"
  url = "/en-us/archives/"
  weight = 40

#[[footer]]
#  identifier = "twitter"
#  pre = "x-twitter"
#  url = "https://x.com/sinonome_umi"
#  weight = 200

#[[footer]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/ZhenShuo2021"
#  weight = 300

# -- Sub-Navigation menu --
#[[subnavigation]]
#  name = "標籤"
#  pageRef = "tags"
#  weight = 10
