# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.



[[main]]
  name = "文章"
  pageRef = "/more-articles"
  weight = 10

[[main]]
  name = "TIL"
  pageRef = "til"
  weight = 15

[[main]]
  name = "隨筆"
  pageRef = "jottings"
  weight = 20


[[main]]
  name = '筆記 {{< icon-with-text "link" >}}'
  weight = 30
  url = "https://docs.zsl0621.cc/memo/about"

[[main]]
  name = "Git"
  parent = '筆記 {{< icon-with-text "link" >}}'
  weight = 10
  url = "https://zsl0621.cc/ripgit/"

[[main]]
  name = "Linux"
  parent = '筆記 {{< icon-with-text "link" >}}'
  url = "https://zsl0621.cc/linux-command/intro"
  weight = 20

# [[main]]
#   name = "Git"
#   parent = "筆記"
#   pageRef = "notes/git"
#   weight = 30

[[main]]
  name = "免費軟體"
  parent = '筆記 {{< icon-with-text "link" >}}'
  pageRef = "posts/awesome-free-software"
  weight = 90

[[main]]
  name = "Hugo 小抄"
  parent = '筆記 {{< icon-with-text "link" >}}'
  pageRef = "cheatsheet-hugo"
  weight = 100

[[main]]
  name = "各種小抄"
  parent = '筆記 {{< icon-with-text "link" >}}'
  pageRef = "cheatsheet-misc"
  weight = 200

[[main]]
  name = "標籤"
  pageRef = "tags"
  weight = 1

[[main]]
  name = "分類"
  pageRef = "categories"
  weight = 2

# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.

[[footer]]
  name = "關於本站"
  pageRef = "about"
  weight = 10

#[[footer]]
#  name = "系列文集"
#  pageRef = "series"
#  weight = 35

[[footer]]
  name = "所有文章"
  pageRef = "archives"
  weight = 40

#[[footer]]
#  identifier = "twitter"
#  pre = "x-twitter"
#  url = "https://x.com/sinonome_umi"
#  weight = 200

#[[footer]]
#  identifier = "github"
#  pre = "github"
#  url = "https://github.com/ZhenShuo2021"
#  weight = 300



# -- Sub-Navigation menu --
#[[subnavigation]]
#  name = "小抄"
#  pageRef = "hugo-cheatsheet"
#  weight = 10
